"""Bol sathi analytics.

Revision ID: 3666eb6f9f1c
Revises: c111afcea93a
Create Date: 2025-12-10 13:53:53.351279
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3666eb6f9f1c"
down_revision = "c111afcea93a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_phone", sa.BigInteger(), nullable=True),
        sa.Column("user_flow_id", sa.Integer(), nullable=True),
        sa.Column("flow_uuid", sa.String(length=100), nullable=True),
        sa.Column("flow_name", sa.String(length=255), nullable=True),
        sa.Column("flow_type", sa.String(length=50), nullable=True),
        sa.Column("flow_status", sa.String(length=50), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("USER", "GPT", "BHASHINI", name="actortype"),
            nullable=False,
        ),
        sa.Column(
            "destination",
            sa.Enum("USER", "GPT", "BHASHINI", name="actortype"),
            nullable=False,
        ),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("sequence_in_flow", sa.Integer(), nullable=True),
        sa.Column("entry_activity_key", sa.String(length=255), nullable=True),
        sa.Column("created_on", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_on", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_flow_id"],
            ["user_flows.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("message_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_message_transactions_destination"),
            ["destination"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_flow_uuid"), ["flow_uuid"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_sent_at"), ["sent_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_user_flow_id"),
            ["user_flow_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_message_transactions_user_phone"),
            ["user_phone"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_message_transactions_user_phone"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_user_flow_id"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_source"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_sent_at"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_organization_id"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_flow_uuid"))
        batch_op.drop_index(batch_op.f("ix_message_transactions_destination"))

    op.drop_table("message_transactions")
    # ### end Alembic commands ###
